import BlogPostCard from "@/components/blog-post-card";
import { Metadata } from "next/types";
import { getPosts } from "@/lib/contentful";

export const metadata: Metadata = {
  title: "kadriandev | Blog",
  description: "Generated by create next app",
};

export default async function BlogPostsPage() {
  const data = await getPosts();
  const posts = data.items;
  return (
    <div className="h-full">
      {posts.length === 0 ? (
        <div className="h-4/6 flex justify-center items-center">
          <p>There's nothing here yet. Check back later!</p>
        </div>
      ) : (
        <div className="w-full md:w-1/2 mx-auto flex flex-col gap-8">
          {posts.map((post) => (
            <BlogPostCard
              key={post.sys.id}
              entryId={post.sys.id}
              title={post.fields.title as string}
              createdAt={post.sys.createdAt as string}
              description={post.fields.description as string}
            />
          ))}
        </div>
      )}
    </div>
  );
}
