import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster";
import Particles from "@/components/particles";
import NavBar from "./navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "kadriandev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <header className="fixed flex align-middle justify-end md:justify-center w-full z-50 bg-black">
            <NavBar />
          </header>
          <main className="flex h-screen flex-col pt-10 md:pt-10">
            <div className="py-8 md:pt-0 px-4 md:px-14 h-full w-full md:mt-32">
              {children}
            </div>
            <Particles
              className="absolute h-full inset-0 -z-10 animate-fade-in"
              quantity={100}
            />
          </main>
          <Toaster />
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
